- repo: https://github.com/asottile/pyupgrade
  rev: v2.25.0
  hooks:
  - id: pyupgrade
    args: [--py37-plus]
- repo: https://github.com/python/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.0
  hooks:
  - id: flake8
