#!/bin/bash
# bash script for running pylint within $1 or .
# (c) Thomas Spura, 2010

# Explanations:

# C0103: Invalid name
# C0111: Missing docstring
# C0301: Line too long
# C0302: Too many lines in module

# R0904: Too many public methods
# R0912: Too many branches
# R0915: Too many statements

# W0614: Unused import

if [ $# = 1 ]
then
    command=$(find $1 -name "*.py")
else
    command=$(find . -name "*.py")
fi

pylint --msg-template='{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}' \
    --disable=C0111 \
    --disable=C0302 \
    --disable=R0904 \
    --disable=R0912 \
    --disable=R0915 \
    $command

# --errors-only
