#!/usr/bin/python3
'''import main function from gbirthday and execute it'''
try:
    from gbirthday import main
except ImportError:
    # maybe it's installed in a private location
    import os, sys
    usr_share_path = os.path.join('/', 'usr', 'share', 'gbirthday')
    if os.path.exists(usr_share_path):
        sys.path.insert(0, usr_share_path)
        from gbirthday import main
main()
